version: '3'

services:
  nginx:
    build: nginx
    ports:
      - "8888:80"
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_ADMIN: user
      KEYCLOAK_ADMIN_PASSWORD: bitnami
      KC_LOG_LEVEL: INFO
    ports:
      - "8080:8080"
    command:
      - start-dev